/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.asenka.detektor;

import fr.asenka.detektor.util.Matrix;

public class App {

	public static void main(String[] args) {

		Matrix m = new Matrix("1 1 1 ; 1 1 1 ; 1 1 1");
		
		Matrix p = m.concatH(new Matrix("1 ; 2 ; 3"));
		
		System.out.println(m);
		System.out.println(p);
		
		
	}
}
