/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.asenka.detektor;

import fr.asenka.detektor.util.Matrix;

public class App {

	public static void main(String[] args) {

		DataSet trainingData = new DataSet("src/main/resources/train-images-idx3-ubyte.gz",
				"src/main/resources/train-labels-idx1-ubyte.gz");

		Matrix X = trainingData.getVectorizedImages().scale();
		Matrix y = trainingData.getVectorizedLabels().transpose();

		NeuralNetwork nn = new NeuralNetwork(28 * 28, 10, 25);
		
		Matrix p = nn.predict(X);
		
		System.out.println(y);
		System.out.println(p);
	}
}
