/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.asenka.detektor;

import fr.asenka.detektor.util.Matrix;

public class App {

	public static void main(String[] args) {

		Matrix m = new Matrix("1 1 1 ; 1 1 1 ; 1 1 1");
		Matrix p = new Matrix("1 ; 2 ; 3");
		
		System.out.println(m);
		System.out.println(p);
		System.out.println(Matrix.zeros(3, 1).concatHorizontaly(m).concatHorizontaly(p));
		
	}
}
